sudo: required

services:
 - docker

before_install:
 - docker-compose --file docker/ build

script:
 - docker-compose --file docker/ up
 - docker-compose --file docker/ down

deploy:
 - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: docs
   on:
    branch: dev