sudo: required

services:
 - docker

before_install:
 - docker-compose --file docker/docker-compose.yml build

script:
 - docker-compose --file docker/docker-compose.yml up qt5 qmake && make check
 - docker-compose --file docker/docker-compose.yml down

deploy:
 - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: docs
   on:
    branch: dev