sudo: required

services:
 - docker

before_install:
 # To install the Docker plugin 'local-persist':
 # see https://github.com/CWSpear/local-persist
 - curl -fsSL https://raw.githubusercontent.com/CWSpear/local-persist/master/scripts/install.sh | sudo bash
 - docker volume create -d local-persist -o mountpoint=${TRAVIS_BUILD_DIR} --name=source-data 
 - docker-compose --file docker/docker-compose.yml build

script:
 - docker-compose --file docker/docker-compose.yml run test
 - docker-compose --file docker/docker-compose.yml run docs

deploy:
 - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: docs
   on:
    branch: dev