sudo: required

services:
 - docker

before_install:
 # To install the Docker plugin 'local-persist':
 # see https://github.com/CWSpear/local-persist
 - curl -ofsSL https://github.com/CWSpear/local-persist/releases/download/v1.3.0/local-persist-linux-amd64
 - sudo mv local-persist-linux-amd64 /usr/bin/docker-volume-local-persist
 - sudo chmod +x /usr/bin/docker-volume-local-persist
 - curl -o https://github.com/CWSpear/local-persist/blob/master/init/systemd.service
 - sudo mv systemd.service /etc/systemd/system/docker-volume-local-persist.service
 - sudo systemctl daemon-reload
 - sudo systemctl enable docker-volume-local-persist
 - sudo systemctl start docker-volume-local-persist
 - docker volume create -d local-persist -o mountpoint=${TRAVIS_BUILD_DIR} --name=source-data 
 - docker-compose --file docker/docker-compose.yml build

script:
 - docker-compose --file docker/docker-compose.yml run test
 - docker-compose --file docker/docker-compose.yml run docs

deploy:
 - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: docs
   on:
    branch: dev