sudo: required

services:
 - docker

before_install:
 - docker build -t qt:linux docker/linux/
 - docker build -t qt-test:linux docker/linux/test/

script:
 - docker run --rm -v ${TRAVIS_BUILD_DIR}:/source qt-test:linux