sudo: required

services:
 - docker

before_install:
 - docker-compose --file docker/docker-compose.yml build

script:
 - docker-compose --file docker/docker-compose.yml run echo
 - docker-compose --file docker/docker-compose.yml run test
 - docker-compose --file docker/docker-compose.yml run docs

deploy:
 - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: docs
   on:
    branch: dev