sudo: required

services:
 - docker

before_install:
 # Need to install local-persist. See: https://github.com/CWSpear/local-persist
 - curl -fsSL https://raw.githubusercontent.com/CWSpear/local-persist/master/scripts/install.sh | sudo bash -s -- --upstart
 - docker volume create -d local-persist -o mountpoint=${TRAVIS_BUILD_DIR} --name=source-data 

script:
 - docker-compose -f docker/docker-compose.yml -f docker/docker-compose.linux.yml run test
 - docker-compose -f docker/docker-compose.yml run docs

deploy:
 - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: docs
   on:
    branch: dev