FROM ubuntu:trusty
RUN apt-add-repository ppa:beineri/opt-qt591-trusty && \
    apt-update && apt-get upgrade -y && apt-get install -y \
    build-essential \
    libgl1-mesa-dev \
    qt59-meta-minimal